import numpy as np
n=np.array([[1,2,3],[4,5,6],[7,8,9]])
print('对数组元素求和：',n.sum())
print('对数组元素按行求和：',n.sum(axis=1))
print('对数组元素按列求和：',n.sum(axis=0))
print('对数组元素求平均值：',n.mean())
print('对数组元素按行求平均值：',n.mean(axis=1))
print('对数组元素按列求平均值：',n.mean(axis=0))
print('数组元素最大值：',n.max())
print('数组中每一行的最大值：',n.max(axis=1))
print('数组中每一列的最大值：',n.max(axis=0))
print('数组元素最小值：',n.min())
print('数组中每一行的最小值：',n.min(axis=1))
print('数组中每一列的最小值：',n.min(axis=0))